### ISSUE TITLE
Packages getting replaced automatically

### ISSUE THREAD

**Issue by solomonsjoseph** [compbiomed/BatchQC#54]
> library(BatchQC)
Warning message:
replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘BatchQC’ 

When importing BatchQC this warning message is showing up. It could be happening due to usage of deprecated functions in ggplot2 which is last_plot which could have been moved to a newer package called plotly. 
There might be some more packages which might need to get updated but as of now this warning came for one of such package.

**Comment by jessmcc22** [comment]
#58 Corrected warning message

**Comment by jessmcc22** [comment]
https://github.com/compbiomed/BatchQC/pull/58 Corrected warning message
